### PR TITLE
pep8 cleanup

### PR DESCRIPTION
**Pull request by michaelkuty**

### CODE REVIEW

**Comment by jonzlin95** [comment]
You might want to try merging this into the Main branch (Jezdez/django-constance) too. Though he hasn't maintained the repo in a while.

**Comment by michaelkuty** [comment]
no it's merged via your pull reuqest see https://github.com/jezdez/django-constance/pull/96/commits
but i know, @jezdez fuck up to community now..

**Comment by jezdez** [comment]
:ok_hand:

**Comment by michaelkuty** [comment]
sorry man, i understand you, but you don't communicate with community,
if you say i haven't time all is ok but you must set some maintainer for your project which is really good and thanks for your work ! it's issue not only for this but dbtemplates has same problem

**Pull request merged**
